server:
  port: 8080 
spring:
  application:
    name: ${appName:mymicroservice}
  profiles:
    active: ${environmentName:LCL}  
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
  endpoint:
    health:
      probes:
        enabled: true
