logging: 
  level: 
    org.springframework.context.annotation: DEBUG
    org.springframework.core.io.support: DEBUG
    org.springframework.web: TRACE
sample: 
  property: "Sample Property Local"
spring: 
  data: 
    mongodb: 
      database: met-dev
      uri: "mongodb+srv://met-dev:gKCJXDDFyojzmfzZ@cluster0.8uzt77x.mongodb.net/?retryWrites=true&w=majority"
  servlet: 
    multipart: 
      max-file-size: -1
      max-request-size: -1
